### ISSUE TITLE
Multiple bugs with IPG and MTR diffs

### ISSUE THREAD

**Issue by durandg12** [Villawhatever/VensersJournal#12]
Hi Andrew,

First there is a general bug with every IPG and MTR diffs.
Nothing is clickable anymore, I can't display or hide any section. I'm using Firefox 74.0.

There are two small errors in the IKO IPG diff in the Deck Problem section. There are two opening parentheses here:

> (and and any missing cards are not in the opponent’s deck( 

The second one should be closing. And the paragraph about the additional remedy for companions is not highlighted in green as it should be:

> If the error caused a violation of a companion restriction and it is a post-sideboard game (or a pre-sideboard game and the player has elected to continue with the deck they registered that does not match the revealed companion condition), choose at random from cards in the sideboard that meet the companion restriction; the opponent decides where each chosen card goes. If making the deck match the companion condition is impossible, upgrade the penalty to a Game Loss.

There is a small error in the IKO MTR diff. In section 3.2 Pioneer is highlighted in green whereas this is not a change from THB MTR.

Thanks.

**Comment by Villawhatever** [comment]
Howdy!

- Fixed IPG and MTR typos. Thanks.
- Apparently there was a change in... I don't know. web spec or something? Apparently a number is no longer a valid tag, so I need to rename all of the anchors. I have the current IPG and MTR fixed, and I'll handle the archived ones after work. Good catch!

**Comment by Villawhatever** [comment]
So "after work" turned into, uh, later. Work and school have both been a nightmare.
Fixed the div IDs so everything in the archives _should_ be collapsing/expanding properly now.
