### ISSUE TITLE
clues, investigate and rule deletion in the new diff

### ISSUE THREAD

**Issue by durandg12** [Villawhatever/VensersJournal#33]
In the Oracle update bulletin [(link)](https://magic.wizards.com/en/articles/archive/news/comprehensive-rules-changes-2021-06-18) Jess mentions changes to predefined tokens (111.10f) and Investigate (701.36). Those changes do not appear in the new diff.

Also Jess mentions the deletion of rule 702.6d and it also doesn't appear.

**Comment by Villawhatever** [comment]
Fixed Investigate and Clue; I saw they were wrong earlier, but was a little
overeager in deleting them outright. They've been fixed.

702.6c/d are such a complete mess that I'm not sure any version of any
algorithm I could ever write would properly determine what on earth is
going on there. Manually fixed.
