### ISSUE TITLE
Wrong link for MID update bulletin

### ISSUE THREAD

**Issue by fenhl** [Villawhatever/VensersJournal#35]
The link to [the update bulletin for MID](https://magic.wizards.com/en/articles/archive/news/innistrad-midnight-hunt-update-bulletin-2021-09-15) is pointing at [the release notes](https://magic.wizards.com/en/articles/archive/feature/innistrad-midnight-hunt-release-notes-2021-09-15) instead. I'd send a pull request but the repo seems to be outdated compared to the actual website.

**Comment by Villawhatever** [comment]
God, you're not wrong. Fixed.

Also, miss seeing you around IRC. Hope you're well.
