### ISSUE TITLE
minor capitalization issue in the 'about' page on main site

### ISSUE THREAD

**Issue by maallaard** [Villawhatever/VensersJournal#38]
Very minor caps error in [https://vensersjournal.com/about]() that caught my eye. Below is copied from the page:
> Special thanks:
>- Jorge Requesens for providing a massive chunk of the archived tournament docs
>- Arttu Kaipiainen for helping me track down bugs
>- Petr Hudeček for having a giant block of CRs, IPGs, and MTRs available
>- ALl the lovely folx who have donated to keep this site online. <3

Beginning of last bullet point should be 'ALL' not 'ALl'

hope this helped! :)

**Comment by Villawhatever** [comment]
Thank you! Fixed :)
