### ISSUE TITLE
How should I implement the MTR parser?

### ISSUE THREAD

**Issue by multimeric** [Villawhatever/VensersJournal#39]
I'm interested in making an MTR parser for another project, but thought it might be best if I put it here so it can be another API endpoint. Do you have a repo for parsing scripts? I can't find one here. Should it be written in Python? Cheers.

**Comment by Villawhatever** [comment]
I'm currently not diffing the MTR/IPG as part of this project. I'm doing it by hand after comparing the PDFs using something like [Draftable](https://draftable.com/compare)

I haven't had great success with python pdf diffing libraries, but I also don't know much about that ecosystem. I'm working on doing this programmatically with a C# lib, but it's still very WIP. I asked around Thanksgiving about getting the MTR and IPG in *.doc format. If I can convince Scott to let that happen, it should make this process significantly easier.

**Comment by multimeric** [comment]
In terms of the diff, surely it would be reasonable to just use a plaintext differ with the PDF converted to text? This is easily done.

What I'm personally after, though, isn't the diff, but rather a structured JSON version of the MTR which I was hoping you could host. If I can find a way to create a diff while I'm doing this, then I'll certainly try to help out.

**Comment by Villawhatever** [comment]
Oh sure, that's easy enough.

**Comment by multimeric** [comment]
But how should I implement it to fit in way say your CR parser?

**Comment by Villawhatever** [comment]
Right now the CR parsing stuff is all python. It's in the `difftool` folder here https://github.com/Villawhatever/VensersJournal/tree/master/difftool.

Maybe throw it in a `difftool/mtr` folder and go from there?

**Comment by Villawhatever** [comment]
https://github.com/Villawhatever/VensersJournal/blob/master/difftool/diff_utils.py
https://github.com/Villawhatever/VensersJournal/blob/master/difftool/diff_docs.py
https://github.com/Villawhatever/VensersJournal/blob/master/difftool/docs_manip.py

These are all some early, half-hearted attempts and fiddling with the IPG and MTR.

**Comment by multimeric** [comment]
What about the code you use to generate the JSON API? https://api.vensersjournal.com/docs/#/default/getRule

**Comment by Villawhatever** [comment]
https://github.com/Villawhatever/Southfall is where that's all hosted.  `Southfall-v2.js` manages the endpoints, and then the swagger docs are in `reference/`

**Comment by multimeric** [comment]
Right, but where should I put the parser for the MTR, destined for the API?

**Comment by Villawhatever** [comment]
I'd put any work on building a parser, JSON, etc in this repo. Ideally, the Southfall repo goes away entirely and everything is re-homed here.
